// @generated by pi-protocol generate; DO NOT EDIT.
// contract-digest: sha256:b8213e6d3f58ce0754f09d7d3eca930c2c4fe21e5b02f8056c3506931b15be8f
import type { ProtocolAgentExecutor, ProtocolHandler } from "@kybernetria/pi-protocol/core";

export const PROTOCOL_NODE_ID = "pi_cron" as const;
export const PROTOCOL_TARGETS = {
  add: "pi_cron.add",
  edit: "pi_cron.edit",
  delete: "pi_cron.delete",
  list: "pi_cron.list",
  get: "pi_cron.get",
  enable: "pi_cron.enable",
  disable: "pi_cron.disable",
  run_now: "pi_cron.run_now",
} as const;

export type ProtocolProvideName = "add" | "edit" | "delete" | "list" | "get" | "enable" | "disable" | "run_now";
export type ProtocolBinding = ProtocolHandler | ProtocolAgentExecutor;
export type ProtocolBindings = {
  "add": ProtocolBinding;
  "edit": ProtocolBinding;
  "delete": ProtocolBinding;
  "list": ProtocolBinding;
  "get": ProtocolBinding;
  "enable": ProtocolBinding;
  "disable": ProtocolBinding;
  "run_now": ProtocolBinding;
};

export type AddInput = { job: { action: Record<string, never>; enabled: boolean; id?: string; name: string; schedule: string; timezone: string; }; };
export type AddOutput = Record<string, never>;
export type EditInput = { job: { action: Record<string, never>; enabled: boolean; id: string; name: string; schedule: string; timezone: string; }; };
export type EditOutput = Record<string, never>;
export type DeleteInput = { id: string; };
export type DeleteOutput = { deleted: boolean; id: string; };
export type ListInput = Record<string, never>;
export type ListOutput = readonly Record<string, never>[];
export type GetInput = { id: string; };
export type GetOutput = { job: Record<string, never>; occurrences: readonly Record<string, never>[]; };
export type EnableInput = { id: string; };
export type EnableOutput = Record<string, never>;
export type DisableInput = { id: string; };
export type DisableOutput = Record<string, never>;
export type RunNowInput = { id: string; };
export type RunNowOutput = Record<string, never>;
